name: Build and Deploy Docs Stage Branch
on:
  push:
    branches:
      - stage
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Download Latest Awesome repo README
        run: curl https://raw.githubusercontent.com/osmosis-labs/awesome/main/README.md > awesome/README.md

      - name: Install and Build 🔧 # This will create version inside the 'build' folder.
        run: |
          npm install
          npm run build

      - name: Deploy to Stage Branch 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: stage-build # The branch the action should deploy to.
          folder: .vuepress/dist
